name: Slack Notifier
description: Sends a message to Slack
inputs:
  github_workflow:
    required: true
  github_repository:
    required: true
  github_run_id:
    required: true
  github_job:
    required: true
  step_conclusion:
    required: true
  slack_webhook:
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        echo "Sending Slack notification for failed steps."

        COLOR="#FF0000"
        ATTACHMENT=$(cat <<EOF
        {
          "attachments": [
            {
              "color": "${COLOR}",
              "title": "GitHub Workflow in ${{ inputs.step_conclusion }} state for ${{ inputs.github_repository }}",
              "title_link": "https://github.com/${{ inputs.github_repository }}",
              "fields": [
                {
                  "value": "Failed Workflow \"${{ inputs.github_workflow }}\": https://github.com/${{ inputs.github_repository }}/actions/runs/${{ inputs.github_run_id }}"
                },
                {
                  "value": "Failed Job \"${{ inputs.github_workflow }}\": https://github.com/${{ inputs.github_repository }}/actions/runs/${{ inputs.github_run_id }}/job/${{ inputs.github_job }}"
                }                
              ],
              "footer": "Dashboard: n/a"
            }
          ]
        }
        EOF
        )

        curl -s -X POST -H "Content-type: application/json" --data "$ATTACHMENT" "${{ inputs.slack_webhook }}"
      shell: bash  
