name: Slack Notifier
description: Sends a message to Slack
inputs:
  github_workflow:
    required: true
  github_repository:
    required: true
  github_run_id:
    required: true  
  step_conclusion:
    required: true
  slack_webhook:
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        echo "Sending Slack notification for failed steps."

        COLOR="#FF0000"
        ATTACHMENT=$(cat <<EOF
        {
          "attachments": [
            {
              "color": "${COLOR}",
              "title": "SecureSDLC GitHub Workflow ${{ inputs.github_workflow }} state: ${{ inputs.step_conclusion }}",
              "title_link": "https://github.com/${{ inputs.github_repository }}",
              "fields": [
                {
                  "value": "GitHub Workflow: https://github.com/${REPOSITORY}/actions/runs/${{ inputs.github_run_id }}"
                }
              ],
              "footer": "Dashboard: https://grafana.ops.kraken.zone/dashboards/f/tf-appsec/devsecops"
            }
          ]
        }
        EOF
        )

        curl -s -X POST -H "Content-type: application/json" --data "$ATTACHMENT" "${{ inputs.slack_webhook }}"
      shell: bash  
