name: Slack Notifier
description: Sends a message to Slack
inputs:
  github_workflow:
    required: true
  github_repository:
    required: true
  github_run_id:
    required: true  
  step_conclusion:
    required: true
  slack_webhook:
    required: true

runs:
  using: "composite"
  steps:
    - run: ./notify.sh \
        "${{ inputs.github_workflow }}" \
        "${{ inputs.github_repository }}" \
        "${{ inputs.github_run_id }}" \
        "${{ inputs.step_conclusion }}" \        
        "${{ inputs.slack_webhook }}"
      shell: bash  
